application: kevinkipp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stylesheets
  static_dir: stylesheets
  mime_type: "text/css"

- url: /css
  static_dir: css
  mime_type: "text/css"

- url: /js
  static_dir: js
  mime_type: text/javascript

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/ico


- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest